### PR TITLE
feat(lsp): filtered workspace symbol searches

### LINKED ISSUE #198: Commands for filtered workspace symbol searches
### Feature description

https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#workspace-symbols-filtering

### PR DESCRIPTION
**Pull request by mrcjkb**
Closes #198

### CODE REVIEW

**Comment by xzbdmw** [comment]
different of lsp.workspaceymbol

https://github.com/mrcjkb/rustaceanvim/assets/97848247/2b968d25-a8ca-49ce-a54c-551c979c0f17

**Comment by xzbdmw** [comment]
here is config 
```lua 
    server = {
        settings = {
            -- rust-analyzer language server configuration
            ["rust-analyzer"] = {
                inlayHints = {
                    parameterHints = false,
                    closureReturnTypeHints = true,
                },
                workspace = {
                    symbol = {
                        search = {
                            scope = "workspace_and_dependencies",
                        },
                    },
                },
            },
        },
    },

```

**Comment by mrcjkb** [comment]
> here is config
> 
> ```lua
>     server = {
>         settings = {
>             -- rust-analyzer language server configuration
>             ["rust-analyzer"] = {
>                 inlayHints = {
>                     parameterHints = false,
>                     closureReturnTypeHints = true,
>                 },
>                 workspace = {
>                     symbol = {
>                         search = {
>                             scope = "workspace_and_dependencies",
>                         },
>                     },
>                 },
>             },
>         },
>     },
> ```

Yes, if you have the default scope set to `workspace_and_dependencies` in rust-analyzer's settings (this is not the default), `:RustLsp workspaceSymbol allSymbols` will behave differently.
You can include dependencies in your search by running `:RustLsp! workspaceSymbol` (with a bang).

**Comment by xzbdmw** [comment]
It seems `vim.lsp.buf.workspace_symbols` will perform an exact match while `Rustlsp!` behave the same as vscode(fuzzy match).

**Comment by xzbdmw** [comment]
`vim.lsp.buf.workspace_symbols + query#` behaves like `Rustlsp! workspaceSymbol allSymbols`
and `vim.lsp.buf.workspace_symbols + query` behaves like `Rustlsp! workspaceSymbol onlyTypes`

**Pull request merged**
