### PR TITLE
fix(dap): lldb library paths are strings

### LINKED ISSUE #73: Dynamic linking breaks again
Something might have shifted between when we merged the dynamic PR and when it hit release... I seem to have a regression that's not there on my local copy. Debugging Bevy exits right away with nothing in `:messages`. Lookin' into it :sunglasses:

### PR DESCRIPTION
**Pull request by richchurcher**
###### Description of changes

This:
- [x] switches paths back to strings, `lldb` is fussy about this apparently

I can't promise this is also true for code-lldb? But it seems likely. Tests are still green.

Fixes #73

###### Things done

- [x] Tested, as applicable:
  - [x] Manually
  - [ ] Added `busted` specs
- [x] Fits [CONTRIBUTING.md](https://github.com/mrcjkb/rustaceanvim/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by mrcjkb — CHANGES_REQUESTED** [review]
We'll have to make this dependent on whether we're using `lldb` (`adapter.type == 'executable'`) or `codelldb` (`adapter.type == 'server'`).

I would suggest to convert the map into a list of strings if (`adapter.type == 'executable'`).

**Comment by mrcjkb** [comment]
PS, do you have a project I can test this on (ideally with steps to reproduce, for when I implement an integration test)?

**Comment by richchurcher** [comment]
Yeah, good idea: I'll see what the smallest possible example with dynamic linking is, no sense in throwing all of Bevy at it.

**Comment by richchurcher** [comment]
> (see https://github.com/mrcjkb/rustaceanvim/pull/64#pullrequestreview-1749830630).
Shoot, sry I missed that one in all the confusion :slightly_smiling_face:

**Comment by richchurcher** [comment]
https://github.com/richchurcher/test-rustaceanvim reproduces the problem. I forgot that there's a dynamic linking feature in Bevy specifically, so did need to include it. Let me know if you want me to leave it there indefinitely or remove it.

**Comment by mrcjkb** [comment]
> https://github.com/richchurcher/test-rustaceanvim reproduces the problem. I forgot that there's a dynamic linking feature in Bevy specifically, so did need to include it. Let me know if you want me to leave it there indefinitely or remove it.

Thanks :pray:

I'll have to pick this up on Friday, but if you're okay with it, we can add it to this repo under a `spec/fixtures/dap/dynamic-libs` directory.

**Comment by richchurcher** [comment]
> I'll have to pick this up on Friday, but if you're okay with it, we can add it to this repo under a `spec/fixtures/dap/dynamic-libs` directory.

:100: 

The latest commit seems to do the trick. Managing a `codelldb` install is a giant PITA though... is that something the nix flakes can help with? I can confirm it works with `lldb-dap`.

**Comment by mrcjkb** [comment]
> The latest commit seems to do the trick. 

Just tested it with `codelldb` and `lldb` (using your test project) and it works for both on my machine.
Thanks for the great work! :pray: 

> Managing a codelldb install is a giant PITA though... is that something the nix flakes can help with?

The `codelldb` standalone adapter is currently broken in nixpkgs (it only works when used with the VSCode plugin). I have [an open PR](https://github.com/NixOS/nixpkgs/pull/264887) that fixes it, but it's a bit hacky.
For now, I've been running:
```
nix shell "github:mrcjkb/nixpkgs/codelldb-fix#vscode-extensions.vadimcn.vscode-lldb.adapter"
```
to enter a shell with the adapter from my fork.
There's also an AUR package for Arch (which I haven't tested).

**Review by mrcjkb — APPROVED** [review]

**Pull request merged**
